from redis import StrictRedis

red = StrictRedis(host='localhost', port=6379)

red.delete('LIVE_PRICE:BTC')
red.delete('LIVE_PRICE:ETH')
red.delete('LIVE_PRICE:USDT')
red.delete('LIVE_PRICE:BNB')
red.delete('LIVE_PRICE:SOL')
red.delete('LIVE_PRICE:USDC')
red.delete('LIVE_PRICE:XRP')
red.delete('LIVE_PRICE:STETH')
red.delete('LIVE_PRICE:WTRX')
red.delete('LIVE_PRICE:DOGE')
red.delete('LIVE_PRICE:TRX')
red.delete('LIVE_PRICE:TON11419')

red.delete('LIVE_VOLUME:BTC')
red.delete('LIVE_VOLUME:ETH')
red.delete('LIVE_VOLUME:USDT')
red.delete('LIVE_VOLUME:BNB')
red.delete('LIVE_VOLUME:SOL')
red.delete('LIVE_VOLUME:USDC')
red.delete('LIVE_VOLUME:XRP')
red.delete('LIVE_VOLUME:STETH')
red.delete('LIVE_VOLUME:WTRX')
red.delete('LIVE_VOLUME:DOGE')
red.delete('LIVE_VOLUME:TRX')
red.delete('LIVE_VOLUME:TON11419')